# Generated by Django 4.1.7 on 2023-05-30 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0002_alter_category_options_iteme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iteme',
            new_name='Item',
        ),
    ]
